import {
  // ElAffix,
  // ElAside,
  ElAutocomplete,
  ElAvatar,
  ElBreadcrumb,
  // ElBreadcrumbItem,
  ElButton,
  // ElButtonGroup,
  ElCard,
  ElCheckbox,
  ElCheckTag,
  ElCol,
  ElCollapse,
  // ElCollapseItem,
  ElContainer,
  ElDatePicker,
  ElDescriptions,
  // ElDescriptionsItem,
  ElDialog,
  ElDivider,
  ElDrawer,
  // ElFooter,
  ElForm,
  // ElFormItem,
  // ElHeader,
  ElIcon,
  ElImage,
  ElInfiniteScroll,
  ElInput,
  ElInputNumber,
  ElLoading,
  // ElMain,
  ElMenu,
  // ElMenuItem,
  // ElMenuItemGroup,
  ElMessage,
  ElMessageBox,
  ElNotification,
  // ElOption,
  ElPagination,
  ElPopconfirm,
  ElPopover,
  ElRadio,
  ElRow,
  ElScrollbar,
  ElSelect,
  ElSpace,
  // ElSubmenu,
  ElSwitch,
  ElTable,
  // ElTableColumn,
  ElTag,
  // ElTimeline,
  ElTimeline,
  // ElTimelineItem,
  ElTooltip,
  ElTree,
  ElUpload,
} from 'element-plus/lib/components';
import makeInstaller from 'element-plus/lib/make-installer';

export const components = [
  // ElAffix,
  // ElAside,
  ElAutocomplete,
  ElAvatar,
  ElBreadcrumb,
  // ElBreadcrumbItem,
  ElButton,
  // ElButtonGroup,
  ElCard,
  ElCheckbox,
  ElCheckTag,
  ElCol,
  ElCollapse,
  // ElCollapseItem,
  ElContainer,
  ElDatePicker,
  ElDescriptions,
  // ElDescriptionsItem,
  ElDialog,
  ElDivider,
  ElDrawer,
  // ElFooter,
  ElForm,
  // ElFormItem,
  // ElHeader,
  ElIcon,
  ElImage,
  ElInput,
  ElInputNumber,
  // ElMain,
  ElMenu,
  // ElMenuItem,
  // ElMenuItemGroup,
  // ElOption,
  ElPagination,
  ElPopconfirm,
  ElPopover,
  ElRadio,
  ElRow,
  ElScrollbar,
  ElSelect,
  ElSpace,
  // ElSubmenu,
  ElSwitch,
  ElTable,
  // ElTableColumn,
  ElTag,
  ElTimeline,
  // ElTimelineItem,
  ElTooltip,
  ElTree,
  ElUpload,
];

export const plugins = [ElInfiniteScroll, ElLoading, ElMessage, ElMessageBox, ElNotification];

export const setupElementPlusComponents = makeInstaller(components);
export const setupElementPlusPlugins = makeInstaller(plugins);
